name: weatherbench
channels:
  - conda-forge
dependencies:
  - python=3.6
  - xarray
  - netcdf4
  - dask
  - xesmf
  - fire
  - numpy
  - matplotlib
  - seaborn
  - configargparse
  - tensorflow=2.1
  - pip:
      - cdsapi