exp_id: 28.1-resnet_bn_mid_no_bias
datadir: /data/stephan/WeatherBench/5.625deg/
model_save_dir: /home/stephan/data/myWeatherBench/predictions/saved_models/
pred_save_dir: /home/stephan/data/myWeatherBench/predictions/
var_dict: {'geopotential': ('z', [500]), 'temperature': ('t', [850]), 'constants': ['lsm','orography','lat2d']}
output_vars: [z_500, t_850]
filters: [128, 128, 128, 128, 128, 128, 128, 128, 2]
kernels: [7, 3, 3, 3, 3, 3, 3, 3, 3]
lead_time: 72
lr: 0.5e-4
early_stopping_patience: 5
norm_subsample: 60000
epochs: 150
network_type: resnet
activation: relu
bn_position: mid
batch_size: 64
use_bias: False
