exp_id: 06-decay_10_5
datadir: /data/stephan/WeatherBench/5.625deg/
model_save_dir: /home/stephan/data/myWeatherBench/predictions/saved_models/
pred_save_dir: /home/stephan/data/myWeatherBench/predictions/
var_dict: {'geopotential': ('z', [500]), 'temperature': ('t', [850])}
filters: [64, 64, 64, 64, 2]
kernels: [5, 5, 5, 5, 5]
lead_time: 72
lr: 2.5e-4
lr_step: 10
lr_divide: 5
norm_subsample: 60000
epochs: 150
